compatibility_date = "2024-10-10"
name = "qiita-hackathon-2024-09-backend"
send_metrics = false

[[env.dev.d1_databases]]
binding = "DB"
database_name = "qiita-hackathon-2024-09"
database_id = "3e26f83d-e59f-419b-92cd-03250ec8a99b"

[[env.production.d1_databases]]
binding = "DB"
database_name = "qiita-hackathon-2024-09"
database_id = "3e26f83d-e59f-419b-92cd-03250ec8a99b"

[[env.production.r2_buckets]]
binding = 'BUCKET'
bucket_name = 'qiita-hackathon-images'
preview_bucket_name = 'qiita-hackathon-images'

[[env.dev.r2_buckets]]
binding = 'BUCKET'
bucket_name = 'qiita-hackathon-images'
preview_bucket_name = 'qiita-hackathon-images'

[env.production.ai]
binding = "AI"

[env.dev.ai]
binding = "AI"

[env.dev.vars]
ENVIROMENT = "dev"

[env.production.vars]
ENVIROMENT = "production"

[observability]
enabled = true
